version: '3.8'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./data/conf.d:/etc/mysql/conf.d
      - ./data/logs:/logs
      - accounts_database_volume:/var/lib/mysql #saves the database on server
    networks:
    - server-internal-communication

  api:
    build: ./API
    container_name: accounts_api
    env_file:
      - .env
    restart: always
    depends_on:
      - mysql
    #waits for the mysql container
    networks:
      - server-internal-communication

networks:
  server-internal-communication:
    external: true

volumes:
  accounts_database_volume: #permanent independent volume